apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-web-demo
spec:
  template:
    spec:
      containers:
      - image: quay.io/tkhussein/nodejs-web-demo:b873b57b5dce18101781d78031c1a3fea142e666
        name: nodejs-web-demo
