apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-web-demo
spec:
  template:
    spec:
      containers:
      - image: quay.io/tkhussein/nodejs-web-demo:d48dd761768b5f0e31cca4f02c9cd145ed98a88a
        name: nodejs-web-demo
