apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-web-demo
spec:
  template:
    spec:
      containers:
      - image: quay.io/tkhussein/nodejs-web-demo:99dd7a9dc6a3c066a1c6b48b4bce31402ba2c1fd
        name: nodejs-web-demo
