apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dotnettest
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      # - cluster: dev-unstable
      #   url: https://kubernetes.default.svc
      #   namespace: php-hello-unstable
      # - cluster: dev
      #   url: https://kubernetes.default.svc
      #   namespace: php-hello
  template:
    metadata:
      name: '{{cluster}}-{{namespace}}-dotnettest'
    spec:
      source:
        repoURL: https://github.com/taiseerhussein/baseline-demo
        targetRevision: main
        path: kustomize/org-services/services/dotnettest/overlays/{{cluster}}
      project: default
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true