apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnettest
spec:
  template:
    spec:
      containers:
      - image: quay.io/tkhussein/dotnettest:080434d98459f8140eef8bd373f679ff32f88790
        name: dotnettest
