apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  creationTimestamp: '2024-05-13T18:30:40Z'
  generation: 1
  managedFields:
    - apiVersion: triggers.tekton.dev/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:params': {}
          'f:resourcetemplates': {}
      manager: Mozilla
      operation: Update
      time: '2024-05-13T18:30:40Z'
  name: trigger-template-php-hello-3h8bta
  namespace: nodejs-web-app-pipelines
  resourceVersion: '1229863'
  uid: e21b7197-197a-4d12-95c2-b6c977432ef8
spec:
  params:
    - name: git-revision
    - name: git-commit-message
    - name: git-repo-url
    - name: git-repo-name
    - name: pusher-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        annotations:
          pipeline.openshift.io/started-by: cluster-admin
        generateName: php-hello-
        labels:
          app.kubernetes.io/instance: pipelines
          tekton.dev/pipeline: php-hello
        namespace: nodejs-web-app-pipelines
      spec:
        params:
          - name: git-url
            value: 'https://github.com/taiseerhussein/php-hello-dockerfile.git'
          - name: git-revision
            value: main
          - name: IMAGEREPO
            value: quay.io/tkhussein/php-hello
          - name: KUSTOMIZE_GIT_URL
            value: 'https://github.com/taiseerhussein/baseline-demo.git'
          - name: KUSTOMIZE_ENV
            value: dev
          - name: IMAGETAG
            value: v3.0.4
          - name: KUSTOMIZE_GIT_REVISION
            value: main
          - name: KUSTOMIZE_GIT_CONTEXT_DIR
            value: kustomize/org-services/services
          - name: KUSTOMIZE_GIT_FILE_NAME
            value: php-hello/overlays/$(params.KUSTOMIZE_ENV)/version.yaml
        pipelineRef:
          name: php-hello
        status: null
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
                storageClassName: gp3
                volumeMode: Filesystem
