apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: trigger-template-nodejs-web-demo-pipeline
  namespace: tekton-tutorial
spec:
  params:
    - name: git-revision
    - name: git-commit-message
    - name: git-repo-url
    - name: git-repo-name
    - name: content-type
    - name: pusher-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        annotations:
          pipeline.openshift.io/started-by: cluster-admin
        generateName: dotnet-pipeline-
        labels:
          app.kubernetes.io/instance: pipelines
          tekton.dev/pipeline: dotnet-pipeline
        namespace: tekton-tutorial
      spec:
        params:
          - name: git-url
            value: 'https://github.com/taiseerhussein/dotnet-test.git'
          - name: git-revision
            value: main
          - name: IMAGEREPO
            value: quay.io/tkhussein/nodejs-web-demo
          - name: KUSTOMIZE_GIT_URL
            value: 'https://github.com/taiseerhussein/baseline-demo.git'
          - name: KUSTOMIZE_ENV
            value: dev
          - name: IMAGETAG
            value: v3.0.4
          - name: KUSTOMIZE_GIT_REVISION
            value: main
          - name: KUSTOMIZE_GIT_CONTEXT_DIR
            value: kustomize/org-services/services
          - name: KUSTOMIZE_GIT_FILE_NAME
            value: nodejs-web-demo/overlays/$(params.KUSTOMIZE_ENV)/version.yaml
        pipelineRef:
          name: dotnet-pipeline
        status: null
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
                storageClassName: gp3
                volumeMode: Filesystem
